<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitd3992612104ed37783fcca6f7d21c2b4
{
    public static $prefixLengthsPsr4 = array (
        'D' =>
        array (
            'DLXPlugins\\CommentEditLite\\' => 27,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'DLXPlugins\\CommentEditLite\\' =>
        array (
            0 => __DIR__ . '/../..' . '/includes',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitd3992612104ed37783fcca6f7d21c2b4::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitd3992612104ed37783fcca6f7d21c2b4::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitd3992612104ed37783fcca6f7d21c2b4::$classMap;

        }, null, ClassLoader::class);
    }
}
